/* 
 * Reveal API v2.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// DocumentViewerSearchCriteria
    /// </summary>
    [DataContract]
    public partial class DocumentViewerSearchCriteria :  IEquatable<DocumentViewerSearchCriteria>, IValidatableObject
    {
        /// <summary>
        /// Gets or Sets QueryType
        /// </summary>
        [DataMember(Name="queryType", EmitDefaultValue=false)]
        public SearchQueryType? QueryType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="DocumentViewerSearchCriteria" /> class.
        /// </summary>
        /// <param name="QueryString">QueryString.</param>
        /// <param name="QueryType">QueryType.</param>
        /// <param name="SortByString">SortByString.</param>
        /// <param name="IgnoreDocumentSecurity">IgnoreDocumentSecurity.</param>
        /// <param name="SearchProfileIds">SearchProfileIds.</param>
        /// <param name="DocumentIndex">DocumentIndex.</param>
        /// <param name="Count">Count.</param>
        public DocumentViewerSearchCriteria(string QueryString = default(string), SearchQueryType? QueryType = default(SearchQueryType?), string SortByString = default(string), bool? IgnoreDocumentSecurity = default(bool?), List<int?> SearchProfileIds = default(List<int?>), int? DocumentIndex = default(int?), int? Count = default(int?))
        {
            this.QueryString = QueryString;
            this.QueryType = QueryType;
            this.SortByString = SortByString;
            this.IgnoreDocumentSecurity = IgnoreDocumentSecurity;
            this.SearchProfileIds = SearchProfileIds;
            this.DocumentIndex = DocumentIndex;
            this.Count = Count;
        }
        
        /// <summary>
        /// Gets or Sets QueryString
        /// </summary>
        [DataMember(Name="queryString", EmitDefaultValue=false)]
        public string QueryString { get; set; }


        /// <summary>
        /// Gets or Sets SortByString
        /// </summary>
        [DataMember(Name="sortByString", EmitDefaultValue=false)]
        public string SortByString { get; set; }

        /// <summary>
        /// Gets or Sets IgnoreDocumentSecurity
        /// </summary>
        [DataMember(Name="ignoreDocumentSecurity", EmitDefaultValue=false)]
        public bool? IgnoreDocumentSecurity { get; set; }

        /// <summary>
        /// Gets or Sets SearchProfileIds
        /// </summary>
        [DataMember(Name="searchProfileIds", EmitDefaultValue=false)]
        public List<int?> SearchProfileIds { get; set; }

        /// <summary>
        /// Gets or Sets DocumentIndex
        /// </summary>
        [DataMember(Name="documentIndex", EmitDefaultValue=false)]
        public int? DocumentIndex { get; set; }

        /// <summary>
        /// Gets or Sets Count
        /// </summary>
        [DataMember(Name="count", EmitDefaultValue=false)]
        public int? Count { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DocumentViewerSearchCriteria {\n");
            sb.Append("  QueryString: ").Append(QueryString).Append("\n");
            sb.Append("  QueryType: ").Append(QueryType).Append("\n");
            sb.Append("  SortByString: ").Append(SortByString).Append("\n");
            sb.Append("  IgnoreDocumentSecurity: ").Append(IgnoreDocumentSecurity).Append("\n");
            sb.Append("  SearchProfileIds: ").Append(SearchProfileIds).Append("\n");
            sb.Append("  DocumentIndex: ").Append(DocumentIndex).Append("\n");
            sb.Append("  Count: ").Append(Count).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DocumentViewerSearchCriteria);
        }

        /// <summary>
        /// Returns true if DocumentViewerSearchCriteria instances are equal
        /// </summary>
        /// <param name="input">Instance of DocumentViewerSearchCriteria to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DocumentViewerSearchCriteria input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.QueryString == input.QueryString ||
                    (this.QueryString != null &&
                    this.QueryString.Equals(input.QueryString))
                ) && 
                (
                    this.QueryType == input.QueryType ||
                    (this.QueryType != null &&
                    this.QueryType.Equals(input.QueryType))
                ) && 
                (
                    this.SortByString == input.SortByString ||
                    (this.SortByString != null &&
                    this.SortByString.Equals(input.SortByString))
                ) && 
                (
                    this.IgnoreDocumentSecurity == input.IgnoreDocumentSecurity ||
                    (this.IgnoreDocumentSecurity != null &&
                    this.IgnoreDocumentSecurity.Equals(input.IgnoreDocumentSecurity))
                ) && 
                (
                    this.SearchProfileIds == input.SearchProfileIds ||
                    this.SearchProfileIds != null &&
                    this.SearchProfileIds.SequenceEqual(input.SearchProfileIds)
                ) && 
                (
                    this.DocumentIndex == input.DocumentIndex ||
                    (this.DocumentIndex != null &&
                    this.DocumentIndex.Equals(input.DocumentIndex))
                ) && 
                (
                    this.Count == input.Count ||
                    (this.Count != null &&
                    this.Count.Equals(input.Count))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.QueryString != null)
                    hashCode = hashCode * 59 + this.QueryString.GetHashCode();
                if (this.QueryType != null)
                    hashCode = hashCode * 59 + this.QueryType.GetHashCode();
                if (this.SortByString != null)
                    hashCode = hashCode * 59 + this.SortByString.GetHashCode();
                if (this.IgnoreDocumentSecurity != null)
                    hashCode = hashCode * 59 + this.IgnoreDocumentSecurity.GetHashCode();
                if (this.SearchProfileIds != null)
                    hashCode = hashCode * 59 + this.SearchProfileIds.GetHashCode();
                if (this.DocumentIndex != null)
                    hashCode = hashCode * 59 + this.DocumentIndex.GetHashCode();
                if (this.Count != null)
                    hashCode = hashCode * 59 + this.Count.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
