/* 
 * Reveal API v2.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// FolderIdCountsRequest
    /// </summary>
    [DataContract]
    public partial class FolderIdCountsRequest :  IEquatable<FolderIdCountsRequest>, IValidatableObject
    {
        /// <summary>
        /// Gets or Sets FolderType
        /// </summary>
        [DataMember(Name="folderType", EmitDefaultValue=false)]
        public FolderItemType? FolderType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="FolderIdCountsRequest" /> class.
        /// </summary>
        /// <param name="FolderType">FolderType.</param>
        /// <param name="Ids">Ids.</param>
        /// <param name="GetSubFolders">GetSubFolders.</param>
        public FolderIdCountsRequest(FolderItemType? FolderType = default(FolderItemType?), List<string> Ids = default(List<string>), bool? GetSubFolders = default(bool?))
        {
            this.FolderType = FolderType;
            this.Ids = Ids;
            this.GetSubFolders = GetSubFolders;
        }
        

        /// <summary>
        /// Gets or Sets Ids
        /// </summary>
        [DataMember(Name="ids", EmitDefaultValue=false)]
        public List<string> Ids { get; set; }

        /// <summary>
        /// Gets or Sets GetSubFolders
        /// </summary>
        [DataMember(Name="getSubFolders", EmitDefaultValue=false)]
        public bool? GetSubFolders { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FolderIdCountsRequest {\n");
            sb.Append("  FolderType: ").Append(FolderType).Append("\n");
            sb.Append("  Ids: ").Append(Ids).Append("\n");
            sb.Append("  GetSubFolders: ").Append(GetSubFolders).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FolderIdCountsRequest);
        }

        /// <summary>
        /// Returns true if FolderIdCountsRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of FolderIdCountsRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FolderIdCountsRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.FolderType == input.FolderType ||
                    (this.FolderType != null &&
                    this.FolderType.Equals(input.FolderType))
                ) && 
                (
                    this.Ids == input.Ids ||
                    this.Ids != null &&
                    this.Ids.SequenceEqual(input.Ids)
                ) && 
                (
                    this.GetSubFolders == input.GetSubFolders ||
                    (this.GetSubFolders != null &&
                    this.GetSubFolders.Equals(input.GetSubFolders))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.FolderType != null)
                    hashCode = hashCode * 59 + this.FolderType.GetHashCode();
                if (this.Ids != null)
                    hashCode = hashCode * 59 + this.Ids.GetHashCode();
                if (this.GetSubFolders != null)
                    hashCode = hashCode * 59 + this.GetSubFolders.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
