/* 
 * Reveal API v1.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = RevealAPI.V1.Client.SwaggerDateConverter;

namespace RevealAPI.V1.Models.Resources
{
    /// <summary>
    /// CaseStatisticsResponse
    /// </summary>
    [DataContract]
    public partial class CaseStatisticsResponse :  IEquatable<CaseStatisticsResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CaseStatisticsResponse" /> class.
        /// </summary>
        /// <param name="caseId">caseId.</param>
        /// <param name="nativeCount">nativeCount.</param>
        /// <param name="imageCount">imageCount.</param>
        /// <param name="nativeSize">nativeSize.</param>
        /// <param name="imagesSize">imagesSize.</param>
        /// <param name="documentsSize">documentsSize.</param>
        /// <param name="databaseSize">databaseSize.</param>
        /// <param name="productionSize">productionSize.</param>
        /// <param name="productionImageCount">productionImageCount.</param>
        /// <param name="indexSize">indexSize.</param>
        /// <param name="userCount">userCount.</param>
        /// <param name="loggedInUserCount">loggedInUserCount.</param>
        /// <param name="nativeErrorCount">nativeErrorCount.</param>
        /// <param name="imageErrorCount">imageErrorCount.</param>
        /// <param name="productionImageErrorCount">productionImageErrorCount.</param>
        /// <param name="endDatetime">endDatetime.</param>
        /// <param name="startDatetime">startDatetime.</param>
        public CaseStatisticsResponse(int? caseId = default(int?), long? nativeCount = default(long?), long? imageCount = default(long?), double? nativeSize = default(double?), double? imagesSize = default(double?), double? documentsSize = default(double?), double? databaseSize = default(double?), double? productionSize = default(double?), long? productionImageCount = default(long?), double? indexSize = default(double?), long? userCount = default(long?), long? loggedInUserCount = default(long?), long? nativeErrorCount = default(long?), long? imageErrorCount = default(long?), long? productionImageErrorCount = default(long?), DateTime? endDatetime = default(DateTime?), DateTime? startDatetime = default(DateTime?))
        {
            this.CaseId = caseId;
            this.NativeCount = nativeCount;
            this.ImageCount = imageCount;
            this.NativeSize = nativeSize;
            this.ImagesSize = imagesSize;
            this.DocumentsSize = documentsSize;
            this.DatabaseSize = databaseSize;
            this.ProductionSize = productionSize;
            this.ProductionImageCount = productionImageCount;
            this.IndexSize = indexSize;
            this.UserCount = userCount;
            this.LoggedInUserCount = loggedInUserCount;
            this.NativeErrorCount = nativeErrorCount;
            this.ImageErrorCount = imageErrorCount;
            this.ProductionImageErrorCount = productionImageErrorCount;
            this.EndDatetime = endDatetime;
            this.StartDatetime = startDatetime;
        }
        
        /// <summary>
        /// Gets or Sets CaseId
        /// </summary>
        [DataMember(Name="caseId", EmitDefaultValue=false)]
        public int? CaseId { get; set; }

        /// <summary>
        /// Gets or Sets NativeCount
        /// </summary>
        [DataMember(Name="nativeCount", EmitDefaultValue=false)]
        public long? NativeCount { get; set; }

        /// <summary>
        /// Gets or Sets ImageCount
        /// </summary>
        [DataMember(Name="imageCount", EmitDefaultValue=false)]
        public long? ImageCount { get; set; }

        /// <summary>
        /// Gets or Sets NativeSize
        /// </summary>
        [DataMember(Name="nativeSize", EmitDefaultValue=false)]
        public double? NativeSize { get; set; }

        /// <summary>
        /// Gets or Sets ImagesSize
        /// </summary>
        [DataMember(Name="imagesSize", EmitDefaultValue=false)]
        public double? ImagesSize { get; set; }

        /// <summary>
        /// Gets or Sets DocumentsSize
        /// </summary>
        [DataMember(Name="documentsSize", EmitDefaultValue=false)]
        public double? DocumentsSize { get; set; }

        /// <summary>
        /// Gets or Sets DatabaseSize
        /// </summary>
        [DataMember(Name="databaseSize", EmitDefaultValue=false)]
        public double? DatabaseSize { get; set; }

        /// <summary>
        /// Gets or Sets ProductionSize
        /// </summary>
        [DataMember(Name="productionSize", EmitDefaultValue=false)]
        public double? ProductionSize { get; set; }

        /// <summary>
        /// Gets or Sets ProductionImageCount
        /// </summary>
        [DataMember(Name="productionImageCount", EmitDefaultValue=false)]
        public long? ProductionImageCount { get; set; }

        /// <summary>
        /// Gets or Sets IndexSize
        /// </summary>
        [DataMember(Name="indexSize", EmitDefaultValue=false)]
        public double? IndexSize { get; set; }

        /// <summary>
        /// Gets or Sets UserCount
        /// </summary>
        [DataMember(Name="userCount", EmitDefaultValue=false)]
        public long? UserCount { get; set; }

        /// <summary>
        /// Gets or Sets LoggedInUserCount
        /// </summary>
        [DataMember(Name="loggedInUserCount", EmitDefaultValue=false)]
        public long? LoggedInUserCount { get; set; }

        /// <summary>
        /// Gets or Sets NativeErrorCount
        /// </summary>
        [DataMember(Name="nativeErrorCount", EmitDefaultValue=false)]
        public long? NativeErrorCount { get; set; }

        /// <summary>
        /// Gets or Sets ImageErrorCount
        /// </summary>
        [DataMember(Name="imageErrorCount", EmitDefaultValue=false)]
        public long? ImageErrorCount { get; set; }

        /// <summary>
        /// Gets or Sets ProductionImageErrorCount
        /// </summary>
        [DataMember(Name="productionImageErrorCount", EmitDefaultValue=false)]
        public long? ProductionImageErrorCount { get; set; }

        /// <summary>
        /// Gets or Sets EndDatetime
        /// </summary>
        [DataMember(Name="endDatetime", EmitDefaultValue=false)]
        public DateTime? EndDatetime { get; set; }

        /// <summary>
        /// Gets or Sets StartDatetime
        /// </summary>
        [DataMember(Name="startDatetime", EmitDefaultValue=false)]
        public DateTime? StartDatetime { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CaseStatisticsResponse {\n");
            sb.Append("  CaseId: ").Append(CaseId).Append("\n");
            sb.Append("  NativeCount: ").Append(NativeCount).Append("\n");
            sb.Append("  ImageCount: ").Append(ImageCount).Append("\n");
            sb.Append("  NativeSize: ").Append(NativeSize).Append("\n");
            sb.Append("  ImagesSize: ").Append(ImagesSize).Append("\n");
            sb.Append("  DocumentsSize: ").Append(DocumentsSize).Append("\n");
            sb.Append("  DatabaseSize: ").Append(DatabaseSize).Append("\n");
            sb.Append("  ProductionSize: ").Append(ProductionSize).Append("\n");
            sb.Append("  ProductionImageCount: ").Append(ProductionImageCount).Append("\n");
            sb.Append("  IndexSize: ").Append(IndexSize).Append("\n");
            sb.Append("  UserCount: ").Append(UserCount).Append("\n");
            sb.Append("  LoggedInUserCount: ").Append(LoggedInUserCount).Append("\n");
            sb.Append("  NativeErrorCount: ").Append(NativeErrorCount).Append("\n");
            sb.Append("  ImageErrorCount: ").Append(ImageErrorCount).Append("\n");
            sb.Append("  ProductionImageErrorCount: ").Append(ProductionImageErrorCount).Append("\n");
            sb.Append("  EndDatetime: ").Append(EndDatetime).Append("\n");
            sb.Append("  StartDatetime: ").Append(StartDatetime).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CaseStatisticsResponse);
        }

        /// <summary>
        /// Returns true if CaseStatisticsResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of CaseStatisticsResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CaseStatisticsResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CaseId == input.CaseId ||
                    (this.CaseId != null &&
                    this.CaseId.Equals(input.CaseId))
                ) && 
                (
                    this.NativeCount == input.NativeCount ||
                    (this.NativeCount != null &&
                    this.NativeCount.Equals(input.NativeCount))
                ) && 
                (
                    this.ImageCount == input.ImageCount ||
                    (this.ImageCount != null &&
                    this.ImageCount.Equals(input.ImageCount))
                ) && 
                (
                    this.NativeSize == input.NativeSize ||
                    (this.NativeSize != null &&
                    this.NativeSize.Equals(input.NativeSize))
                ) && 
                (
                    this.ImagesSize == input.ImagesSize ||
                    (this.ImagesSize != null &&
                    this.ImagesSize.Equals(input.ImagesSize))
                ) && 
                (
                    this.DocumentsSize == input.DocumentsSize ||
                    (this.DocumentsSize != null &&
                    this.DocumentsSize.Equals(input.DocumentsSize))
                ) && 
                (
                    this.DatabaseSize == input.DatabaseSize ||
                    (this.DatabaseSize != null &&
                    this.DatabaseSize.Equals(input.DatabaseSize))
                ) && 
                (
                    this.ProductionSize == input.ProductionSize ||
                    (this.ProductionSize != null &&
                    this.ProductionSize.Equals(input.ProductionSize))
                ) && 
                (
                    this.ProductionImageCount == input.ProductionImageCount ||
                    (this.ProductionImageCount != null &&
                    this.ProductionImageCount.Equals(input.ProductionImageCount))
                ) && 
                (
                    this.IndexSize == input.IndexSize ||
                    (this.IndexSize != null &&
                    this.IndexSize.Equals(input.IndexSize))
                ) && 
                (
                    this.UserCount == input.UserCount ||
                    (this.UserCount != null &&
                    this.UserCount.Equals(input.UserCount))
                ) && 
                (
                    this.LoggedInUserCount == input.LoggedInUserCount ||
                    (this.LoggedInUserCount != null &&
                    this.LoggedInUserCount.Equals(input.LoggedInUserCount))
                ) && 
                (
                    this.NativeErrorCount == input.NativeErrorCount ||
                    (this.NativeErrorCount != null &&
                    this.NativeErrorCount.Equals(input.NativeErrorCount))
                ) && 
                (
                    this.ImageErrorCount == input.ImageErrorCount ||
                    (this.ImageErrorCount != null &&
                    this.ImageErrorCount.Equals(input.ImageErrorCount))
                ) && 
                (
                    this.ProductionImageErrorCount == input.ProductionImageErrorCount ||
                    (this.ProductionImageErrorCount != null &&
                    this.ProductionImageErrorCount.Equals(input.ProductionImageErrorCount))
                ) && 
                (
                    this.EndDatetime == input.EndDatetime ||
                    (this.EndDatetime != null &&
                    this.EndDatetime.Equals(input.EndDatetime))
                ) && 
                (
                    this.StartDatetime == input.StartDatetime ||
                    (this.StartDatetime != null &&
                    this.StartDatetime.Equals(input.StartDatetime))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CaseId != null)
                    hashCode = hashCode * 59 + this.CaseId.GetHashCode();
                if (this.NativeCount != null)
                    hashCode = hashCode * 59 + this.NativeCount.GetHashCode();
                if (this.ImageCount != null)
                    hashCode = hashCode * 59 + this.ImageCount.GetHashCode();
                if (this.NativeSize != null)
                    hashCode = hashCode * 59 + this.NativeSize.GetHashCode();
                if (this.ImagesSize != null)
                    hashCode = hashCode * 59 + this.ImagesSize.GetHashCode();
                if (this.DocumentsSize != null)
                    hashCode = hashCode * 59 + this.DocumentsSize.GetHashCode();
                if (this.DatabaseSize != null)
                    hashCode = hashCode * 59 + this.DatabaseSize.GetHashCode();
                if (this.ProductionSize != null)
                    hashCode = hashCode * 59 + this.ProductionSize.GetHashCode();
                if (this.ProductionImageCount != null)
                    hashCode = hashCode * 59 + this.ProductionImageCount.GetHashCode();
                if (this.IndexSize != null)
                    hashCode = hashCode * 59 + this.IndexSize.GetHashCode();
                if (this.UserCount != null)
                    hashCode = hashCode * 59 + this.UserCount.GetHashCode();
                if (this.LoggedInUserCount != null)
                    hashCode = hashCode * 59 + this.LoggedInUserCount.GetHashCode();
                if (this.NativeErrorCount != null)
                    hashCode = hashCode * 59 + this.NativeErrorCount.GetHashCode();
                if (this.ImageErrorCount != null)
                    hashCode = hashCode * 59 + this.ImageErrorCount.GetHashCode();
                if (this.ProductionImageErrorCount != null)
                    hashCode = hashCode * 59 + this.ProductionImageErrorCount.GetHashCode();
                if (this.EndDatetime != null)
                    hashCode = hashCode * 59 + this.EndDatetime.GetHashCode();
                if (this.StartDatetime != null)
                    hashCode = hashCode * 59 + this.StartDatetime.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
