/* 
 * Reveal API v2.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing JobsprintApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class JobsprintApiTests
    {
        private JobsprintApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new JobsprintApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of JobsprintApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' JobsprintApi
            //Assert.IsInstanceOfType(typeof(JobsprintApi), instance, "instance is a JobsprintApi");
        }

        
        /// <summary>
        /// Test PrintJobsDelete
        /// </summary>
        [Test]
        public void PrintJobsDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? caseId = null;
            //int? id = null;
            //instance.PrintJobsDelete(caseId, id);
            
        }
        
        /// <summary>
        /// Test PrintJobsGetById
        /// </summary>
        [Test]
        public void PrintJobsGetByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? caseId = null;
            //int? id = null;
            //var response = instance.PrintJobsGetById(caseId, id);
            //Assert.IsInstanceOf<PrintJob> (response, "response is PrintJob");
        }
        
        /// <summary>
        /// Test PrintJobsGetList
        /// </summary>
        [Test]
        public void PrintJobsGetListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? caseId = null;
            //int? userId = null;
            //int? start = null;
            //int? count = null;
            //var response = instance.PrintJobsGetList(caseId, userId, start, count);
            //Assert.IsInstanceOf<PaginatedOfIEnumerableOfPrintJob> (response, "response is PaginatedOfIEnumerableOfPrintJob");
        }
        
        /// <summary>
        /// Test PrintJobsPost
        /// </summary>
        [Test]
        public void PrintJobsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? caseId = null;
            //PrintJobCreate body = null;
            //var response = instance.PrintJobsPost(caseId, body);
            //Assert.IsInstanceOf<CreateJobResponse> (response, "response is CreateJobResponse");
        }
        
    }

}
