/* 
 * Reveal API v2.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AssignmentBatchFoldersAssignment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AssignmentBatchFoldersAssignmentTests
    {
        // TODO uncomment below to declare an instance variable for AssignmentBatchFoldersAssignment
        //private AssignmentBatchFoldersAssignment instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AssignmentBatchFoldersAssignment
            //instance = new AssignmentBatchFoldersAssignment();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AssignmentBatchFoldersAssignment
        /// </summary>
        [Test]
        public void AssignmentBatchFoldersAssignmentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AssignmentBatchFoldersAssignment
            //Assert.IsInstanceOfType<AssignmentBatchFoldersAssignment> (instance, "variable 'instance' is a AssignmentBatchFoldersAssignment");
        }


        /// <summary>
        /// Test the property 'FolderIds'
        /// </summary>
        [Test]
        public void FolderIdsTest()
        {
            // TODO unit test for the property 'FolderIds'
        }
        /// <summary>
        /// Test the property 'AssignmentAction'
        /// </summary>
        [Test]
        public void AssignmentActionTest()
        {
            // TODO unit test for the property 'AssignmentAction'
        }
        /// <summary>
        /// Test the property 'AssignedUserId'
        /// </summary>
        [Test]
        public void AssignedUserIdTest()
        {
            // TODO unit test for the property 'AssignedUserId'
        }

    }

}
