/* 
 * Reveal API v2.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ClientManifestProperties
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ClientManifestPropertiesTests
    {
        // TODO uncomment below to declare an instance variable for ClientManifestProperties
        //private ClientManifestProperties instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ClientManifestProperties
            //instance = new ClientManifestProperties();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ClientManifestProperties
        /// </summary>
        [Test]
        public void ClientManifestPropertiesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ClientManifestProperties
            //Assert.IsInstanceOfType<ClientManifestProperties> (instance, "variable 'instance' is a ClientManifestProperties");
        }


        /// <summary>
        /// Test the property 'ClientID'
        /// </summary>
        [Test]
        public void ClientIDTest()
        {
            // TODO unit test for the property 'ClientID'
        }
        /// <summary>
        /// Test the property 'ClientName'
        /// </summary>
        [Test]
        public void ClientNameTest()
        {
            // TODO unit test for the property 'ClientName'
        }
        /// <summary>
        /// Test the property 'CompanyID'
        /// </summary>
        [Test]
        public void CompanyIDTest()
        {
            // TODO unit test for the property 'CompanyID'
        }
        /// <summary>
        /// Test the property 'CompanyName'
        /// </summary>
        [Test]
        public void CompanyNameTest()
        {
            // TODO unit test for the property 'CompanyName'
        }
        /// <summary>
        /// Test the property 'ProjectID'
        /// </summary>
        [Test]
        public void ProjectIDTest()
        {
            // TODO unit test for the property 'ProjectID'
        }
        /// <summary>
        /// Test the property 'ProjectName'
        /// </summary>
        [Test]
        public void ProjectNameTest()
        {
            // TODO unit test for the property 'ProjectName'
        }
        /// <summary>
        /// Test the property 'Api'
        /// </summary>
        [Test]
        public void ApiTest()
        {
            // TODO unit test for the property 'Api'
        }
        /// <summary>
        /// Test the property 'Timezone'
        /// </summary>
        [Test]
        public void TimezoneTest()
        {
            // TODO unit test for the property 'Timezone'
        }
        /// <summary>
        /// Test the property 'Source'
        /// </summary>
        [Test]
        public void SourceTest()
        {
            // TODO unit test for the property 'Source'
        }
        /// <summary>
        /// Test the property 'JobGUID'
        /// </summary>
        [Test]
        public void JobGUIDTest()
        {
            // TODO unit test for the property 'JobGUID'
        }
        /// <summary>
        /// Test the property 'JobPath'
        /// </summary>
        [Test]
        public void JobPathTest()
        {
            // TODO unit test for the property 'JobPath'
        }
        /// <summary>
        /// Test the property 'S3Path'
        /// </summary>
        [Test]
        public void S3PathTest()
        {
            // TODO unit test for the property 'S3Path'
        }
        /// <summary>
        /// Test the property 'CaseID'
        /// </summary>
        [Test]
        public void CaseIDTest()
        {
            // TODO unit test for the property 'CaseID'
        }
        /// <summary>
        /// Test the property 'CreatedBy'
        /// </summary>
        [Test]
        public void CreatedByTest()
        {
            // TODO unit test for the property 'CreatedBy'
        }

    }

}
