/* 
 * Reveal API v2.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing FilterCountRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FilterCountRequestTests
    {
        // TODO uncomment below to declare an instance variable for FilterCountRequest
        //private FilterCountRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FilterCountRequest
            //instance = new FilterCountRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FilterCountRequest
        /// </summary>
        [Test]
        public void FilterCountRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FilterCountRequest
            //Assert.IsInstanceOfType<FilterCountRequest> (instance, "variable 'instance' is a FilterCountRequest");
        }


        /// <summary>
        /// Test the property 'FilterClauses'
        /// </summary>
        [Test]
        public void FilterClausesTest()
        {
            // TODO unit test for the property 'FilterClauses'
        }
        /// <summary>
        /// Test the property 'SearchContext'
        /// </summary>
        [Test]
        public void SearchContextTest()
        {
            // TODO unit test for the property 'SearchContext'
        }

    }

}
