/* 
 * Reveal API v2.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing MetadataFieldFilterOperator
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MetadataFieldFilterOperatorTests
    {
        // TODO uncomment below to declare an instance variable for MetadataFieldFilterOperator
        //private MetadataFieldFilterOperator instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MetadataFieldFilterOperator
            //instance = new MetadataFieldFilterOperator();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MetadataFieldFilterOperator
        /// </summary>
        [Test]
        public void MetadataFieldFilterOperatorInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MetadataFieldFilterOperator
            //Assert.IsInstanceOfType<MetadataFieldFilterOperator> (instance, "variable 'instance' is a MetadataFieldFilterOperator");
        }



    }

}
