/* 
 * Reveal API v2.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TagPaneGet
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TagPaneGetTests
    {
        // TODO uncomment below to declare an instance variable for TagPaneGet
        //private TagPaneGet instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TagPaneGet
            //instance = new TagPaneGet();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TagPaneGet
        /// </summary>
        [Test]
        public void TagPaneGetInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TagPaneGet
            //Assert.IsInstanceOfType<TagPaneGet> (instance, "variable 'instance' is a TagPaneGet");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ProfileId'
        /// </summary>
        [Test]
        public void ProfileIdTest()
        {
            // TODO unit test for the property 'ProfileId'
        }
        /// <summary>
        /// Test the property 'CreatedByUserId'
        /// </summary>
        [Test]
        public void CreatedByUserIdTest()
        {
            // TODO unit test for the property 'CreatedByUserId'
        }
        /// <summary>
        /// Test the property 'CreatedDateTime'
        /// </summary>
        [Test]
        public void CreatedDateTimeTest()
        {
            // TODO unit test for the property 'CreatedDateTime'
        }
        /// <summary>
        /// Test the property 'ModifiedByUserId'
        /// </summary>
        [Test]
        public void ModifiedByUserIdTest()
        {
            // TODO unit test for the property 'ModifiedByUserId'
        }
        /// <summary>
        /// Test the property 'ModifiedDateTime'
        /// </summary>
        [Test]
        public void ModifiedDateTimeTest()
        {
            // TODO unit test for the property 'ModifiedDateTime'
        }
        /// <summary>
        /// Test the property 'TagPaneItems'
        /// </summary>
        [Test]
        public void TagPaneItemsTest()
        {
            // TODO unit test for the property 'TagPaneItems'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'DisplayOrder'
        /// </summary>
        [Test]
        public void DisplayOrderTest()
        {
            // TODO unit test for the property 'DisplayOrder'
        }

    }

}
